name: deploy-mkdocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: pip install --upgrade pip
      - run: pip install --upgrade -r requirements.txt
      - run: mkdocs gh-deploy --force --clean --verbose
